language: java

node_js:
  - "8.2.1"

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

install:
- npm install newman
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test
- node_modules/.bin/newman run postman/cacau.postman_collection.json -e postman/cacau.postman_environment.json

services: mongodb

notifications:
  email: false
