language: java

node_js:
  - "8.2.1"

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

install:
- npm install newman
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test
- nohup java -jar ./target/cacau-api-0.0.1.jar 
- node_modules/.bin/newman run postman/cacau.postman_collection.json -e tests/cacau.postman_environment.json

services: mongodb
